name: CI and CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run CI Tasks
        run: |
          echo "Running CI tasks..."
          # Add your CI tasks here (e.g., tests, builds)
          echo "CI job completed."

  cd:
    name: CD - manial deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy Application
        run: |
          echo "Running CD tasks..."
          echo "Deployment initiated by the CEO"
          # Add your deployment steps here
        env:
          MY_SECRET: ${{ secrets.SECRET_NAME_1 }}
          SECRET: ${{ secrets.SECRET }}
          MY_SECRET_2: ${{ secrets.MY_SECRET_2 }}
          MY_SECRET_1: ${{ secrets.MY_SECRET_1 }}
